In [1]:
import numpy as np 
import matplotlib.pyplot as plt

In [ ]:
import numpy as np  

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]  
sales_data = np.array([  
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani  
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites  
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub  
    [4, 180000, 210000, 240000, 270000],  # Burger Point  
    [5, 160000, 185000, 205000, 230000]   # Chai Point  
])  

print("==== Zomato sales analysis ====")
print("\n Sales data shape: ", sales_data.shape)
print("\n Sample data for first three restaurant:\n ", sales_data[:3])

==== Zomato sales analysis ====

 Sales data shape:  (5, 5)

 Sample data for first three resturant:
  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [ ]:
print(np.sum(sales_data, axis=0))

year_total = np.sum(sales_data[:, 1:], axis=0)
print(year_total)

min_sales_per_restaurant = np.min(sales_data[:, 1:], axis=1)
print(min_sales_per_restaurant)

max_sales_per_year = np.max(sales_data[:, 1:], axis=0)
print(max_sales_per_year)

avg_sales_per_restaurant = np.mean(sales_data[:, 1:], axis=1)
print(avg_sales_per_restaurant)

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]


In [21]:
cumulative_sum = np.cumsum(sales_data[:, 1:], axis=1)
print(cumulative_sum)

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [22]:
# Define vectors
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([6, 7, 8, 9, 10])

# Vector addition
print("Vector addition: ", vector1 + vector2)

# Element-wise multiplication
print("\nMultiplication vector: ", vector1 * vector2)

# Dot product
dot_product = np.dot(vector1, vector2)
print("\nDot Product: ", dot_product)

# Angle between vectors (in radians and degrees)
angle = np.arccos(dot_product / (np.linalg.norm(vector1) * np.linalg.norm(vector2)))
print("\nAngle between vectors (radians):", angle)
print("Angle between vectors (degrees):", np.degrees(angle))


Vector addition:  [ 7  9 11 13 15]

Multiplication vector:  [ 6 14 24 36 50]

Dot Product:  130

Angle between vectors (radians): 0.26554161733900966
Angle between vectors (degrees): 15.214413958603176


In [24]:
restaurant_types = np.array(['biryani','fried rice','oreo','burger','pizza'])

vectorize_op = np.vectorize(str.upper)

print(vectorize_op(restaurant_types))

['BIRYANI' 'FRIED RICE' 'OREO' 'BURGER' 'PIZZA']


## Broadcasting

In [25]:
monthly_avg = sales_data[:, 1:] / 12
print(monthly_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
