## Numpy , arrays and basics
Learning numpy basics and arrays |

In [1]:
import numpy  as np

Creating array from list

In [3]:
arr_1d = np.array([1,2,3])
print("1D array : ", arr_1d)

arr_2d = np.array([[1,2,3] , [4,5,6]])
print("2D array : ", arr_2d)

1D array :  [1 2 3]
2D array :  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [8]:
py_list = [1,2,3]
print("Mltiply of list by 2 : ", py_list*2)

py_array = np.array([1,2,3])
print("Mltiply of array by 2 : ", py_array*2)

import time 

start = time.time()
py_list = [i*2 for i in range(100000000)]
print("\n Run time of py_list: ", time.time()-start)

start = time.time()
py_array = np.arange(100000000) *2
print("\n Run time of py_array: ", time.time()-start)


Mltiply of list by 2 :  [1, 2, 3, 1, 2, 3]
Mltiply of array by 2 :  [2 4 6]

 Run time of py_list:  6.954377174377441

 Run time of py_array:  0.6420471668243408


In [14]:
zeros = np.zeros((4,4))
print("zeros array: \n", zeros)

ones = np.ones((3,3))
print("ones array: \n", ones)

full = np.full((3,3), 7)
print("full array: \n", full)

random = np.random.random((3,3))
print("random array: \n", random)

sequence = np.arange(0,10,2)
print("sequence array: \n", sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
random array: 
 [[0.70324368 0.11050015 0.54022949]
 [0.25054959 0.24415645 0.27639458]
 [0.9790276  0.78941939 0.29281528]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [15]:
Vector = np.array([1,2,3])
print("vector array: \n", Vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix array: \n", matrix)

tensor = np.array([[[1,2], [3,4]],
                  [[5,6],[7,8]],
                  [[8,9],[9,10]]])
print("tensor array: \n", tensor)

vector array: 
 [1 2 3]
matrix array: 
 [[1 2 3]
 [4 5 6]]
tensor array: 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 8  9]
  [ 9 10]]]


### Array properties

In [16]:
arr = np.array([[1,2,3],[4,5,6]])

print("shape ", arr.shape)
print("dimension ", arr.ndim)
print("size ", arr.size)
print("data_type ", arr.dtype)

shape  (2, 3)
dimension  2
size  6
data_type  int64


In [24]:
array = np.arange(9)
print("Array: \n", array)

reshaped = array.reshape((3,3))
print("\n Reshaped array: \n", reshaped)

# return a copy
flattened = reshaped.flatten()
print("\n Flatten array: \n", flattened)

# make changes in the original array and return it
raveled = reshaped.ravel()
print("\n raveled array: \n", raveled)

Transposed = reshaped.T
print("\n Transposed array: \n", Transposed)

Array: 
 [0 1 2 3 4 5 6 7 8]

 Reshaped array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 Flatten array: 
 [0 1 2 3 4 5 6 7 8]

 raveled array: 
 [0 1 2 3 4 5 6 7 8]

 Transposed array: 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
