## Numpy Array Operations

In [20]:
import numpy as np 

In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic_slicing: ", arr[2:7])
print("with step: ", arr[1:8:2])
print("Negative Indexing: ", arr[-3])

Basic_slicing:  [3 4 5 6 7]
with step:  [2 4 6 8]
Negative Indexing:  8


In [22]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific element: ", arr_2d[1,0])
print("Entire row: ", arr_2d[1])
print("Entire col: ", arr_2d[:, 1])

Specific element:  4
Entire row:  [4 5 6]
Entire col:  [2 5 8]


## Sorting

In [23]:
unsorted = np.array([9,6,3,7,1,2,5,2,9,7,3])
print("sorted array: \n", np.sort(unsorted))

unsorted_2d_array = np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array in column:\n ", np.sort(unsorted_2d_array, axis=0))
print("sorted 2d array in row: \n", np.sort(unsorted_2d_array, axis=1))

sorted array: 
 [1 2 2 3 3 5 6 7 7 9 9]
sorted 2d array in column:
  [[1 1]
 [2 2]
 [3 3]]
sorted 2d array in row: 
 [[1 3]
 [1 2]
 [2 3]]


## Filter

In [24]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print(even_numbers)

[ 2  4  6  8 10]


## Filter with mask


In [25]:
mask = numbers > 5
print("numbers greater than 5 : ", numbers[mask])

numbers greater than 5 :  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [26]:
indecis = [0,2,4]
print(numbers[indecis])

where_result = np.where(numbers<5)
print("Numbers lesser then 5: ", numbers[where_result])


[1 3 5]
Numbers lesser then 5:  [1 2 3 4]


In [27]:
condition = np.where(numbers>5,numbers*4, numbers)
print(condition)

[ 1  2  3  4  5 24 28 32 36 40]


## Adding and Removing data


In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Compatibilty array

In [29]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.array([7,8,9])

print("Compatibility test: ", array1.shape == array2.shape)

Compatibility test:  True


In [32]:
original = np.array([[1,2],[3,4]])

new_row = np.array([5,6])

with_new_row = np.vstack((original,new_row))
print(original,"\n")
print(with_new_row,"\n")


original_array = np.array([[1],[3]])

new_column = np.array([[5],[9]])

with_new_column = np.hstack((original_array,new_column))
print(original_array,"\n")
print(with_new_column)

[[1 2]
 [3 4]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1]
 [3]] 

[[1 5]
 [3 9]]


In [35]:
before_deletion = np.array([1,2,3,4,5])
new_arr = np.delete(before_deletion,2)

print("Array after deletion: ",new_arr)

Array after deletion:  [1 2 4 5]
